[build-system]
requires = [
   "setuptools>=69.0",
   "tinysoundfont>=0.3.6",
   "osc4py3>=1.0.8",
   "mido>=1.3.3",
   "numpy>=2.3.2",
   "pyaudio>=0.2.14",
   "PySide6>=6.9.1",
   "sounddevice>=0.5.2",
   "soundfile>=0.13.1",
   "pooch>=1.8",
   "platformdirs>=4.2",
   "pypianoroll>=1.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "CreativePython"
version = "0.0.2"
description = "A Python-based software environment for developing algorithmic art projects."
readme = "README.md"
license = { file = "LICENSE" }
authors = [
	{ name = "Dr. Bill Manaris", email = "manaris@cofc.edu" },
	{ name = "Taj Ballinger", email = "ballingertj@g.cofc.edu" },
	{ name = "Trevor Ritchie", email = "ritchiets@g.cofc.edu" },
]
keywords = ["audio", "midi", "learning", "algorithmic art", "algoart"]
requires-python = ">=3.9"
classifiers = [
	"Programming Language :: Python :: 3",
	"Operating System :: OS Independent",
	"License :: OSI Approved :: MIT License",
]

[project.urls]
Homepage = "https://jythonmusic.me"

[project.scripts]
cp-setup = "creativepython_setup:run"
cp-test = "creativepython_setup:playNote"

[project.optional-dependencies]
dev = ["build", "twine"]
