[package]
name = "canns-ripser"
version = "0.3.2"
edition = "2021"
description = "Rust implementation of Ripser for topological data analysis, optimized for CANNS library"
license = "Apache-2.0"
authors = ["Sichao He <sichaohe@outlook.com>"]
homepage = "https://github.com/routhleck/canns-ripser"
repository = "https://github.com/routhleck/canns-ripser"
keywords = ["topology", "persistent-homology", "tda", "ripser", "canns"]
categories = ["mathematics", "science"]
readme = "README.md"

[lib]
name = "canns_ripser"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.24.2", features = ["extension-module"] }
numpy = "0.24.0"
ndarray = "0.16"
sprs = "0.11"
rayon = { version = "1.8", optional = true }
thiserror = "1.0"
num-traits = "0.2"
indexmap = "2.0"

[build-dependencies]
pyo3-build-config = "0.20"

[dev-dependencies]
approx = "0.5"
criterion = "0.5"


[profile.release]
# Keep default release settings for better compatibility
opt-level = 3
lto = 'fat'
codegen-units = 1
panic = 'abort'
strip = true

[profile.dev]
opt-level = 1

[features]
default = []
parallel = ["rayon"]
debug = []
