[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pasters"
version = "1.0.0"
description = "Minimalistic Python client for paste.rs"
readme = "README.md"
license = { file = "LICENCE" }
requires-python = ">=3.8"
dependencies = ["requests", "httpx"]
authors = [
  { name = "RimMirK", email = "me@RimMirK.pp.ua" }
]
urls = { "Repository" = "https://github.com/RimMirK/pasters" }

keywords = ["paste", "pastes", "paste.rs", "pasters", "code", "pastebin", "client", "share", "send"]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]

[tool.setuptools]
packages = ["pasters"]
include-package-data = true
zip-safe = false
