[project]
name = "mcp-server-dnspod"
version = "0.1.2"
description = "MCP Server for Tencent Cloud DNSPod"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp>=1.0.0",
    "tencentcloud-sdk-python-common==3.0.1375",
    "tencentcloud-sdk-python-dnspod==3.0.1375"
]

[project.scripts]
mcp-server-dnspod = "mcp_server_dnspod:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/mcp_server_dnspod"]
