[package]
name = "jpreprocess-mod-python"
edition = "2021"
version = "0.1.7"

description.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true
readme = "README.md"

[dependencies]
pyo3 = "0.25.1"
pythonize = "0.25.0"

serde.workspace = true
serde_json.workspace = true

jpreprocess-mod.workspace = true
jpreprocess-mod-core.workspace = true
jpreprocess-mod-dictionary.workspace = true
jpreprocess-mod-njd.workspace = true
jpreprocess-mod-jpcommon.workspace = true

lindera.workspace = true
lindera-dictionary.workspace = true
