[project]
name = "evalsync"
version = "0.5.0"
description = "evalsync is a library used to synchronize applications under benchmark with an external manager"
authors = [
    { name = "minhuw", email = "wangmh15@gmail.com" }
]
dependencies = [
    "jinja2>=3.1.5",
    "pyzmq>=27",
    "protobuf>=6.0.0",
    "typer>=0.15.1",
    "loguru>=0.7.3",
]
readme = "README.md"
requires-python = ">= 3.10"

[project.scripts]
evalsyncli = "evalsync.cli:main"

[build-system]
requires = ["hatchling==1.26.3"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "pytest-asyncio>=0.24.0",
    "mypy-protobuf>=3.6.0",
    "pytest-timeout>=2.3.1",
    "ruff>=0.9.5",
    "black>=25.1.0",
    "mypy>=1.0.0",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/evalsync"]
include = ["src/evalsync/py.typed"]

[tool.ruff]
extend-exclude = ["src/evalsync/proto/sync_pb2.py", "src/evalsync/proto/sync_pb2.pyi"]


[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true

[[tool.mypy.overrides]]
module = "evalsync.proto.*"
ignore_errors = true
