[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "zdocker"
version = "1.0.18"
authors = [{name = "Zhiguo.Zhu", email = "294966@qq.com"}]
license = {text = "GPL-3.0-or-later"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
]

description = "It is the build system of linux"
requires-python = ">=3.8, <=3.14"
dependencies = [
    "six >= 1.3.0",
    "docker == 7.1.0",
    "psutil",
    "tqdm",
    "pyserial",
]

[project.scripts]
zdocker = "zdocker:zdocker_main"
zshell = "zdocker:zdocker_main"
cct = "zdocker:cct_main"
