[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "maleo-research"  # PyPI package name
version = "0.0.1"
description = "MaleoResearch service package"
authors = [
    { name = "Agra Bima Yuda", email = "agra@nexmedis.com" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "maleo_soma>=0.1.81"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["maleo.research*"]

[tool.setuptools.package-data]
maleo_research = ["*.json", "*.yaml"]