[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sc-kale"
version = "1.0.0"
authors = [
  { name="Kisan Thapa", email="kisan.thapa001@umb.edu" },
  { name="Ozgun Babur", email="ozgun.babur@umb.edu" },
]
description = "KALE: Cell Activity Inference Landscape"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=2.3.2",
    "pandas>=2.0.0",
    "scanpy>=1.10.0",
    "joblib>=1.5.1",
    "anndata>=0.9.0",
    "scipy>=1.10.0",
    "requests>=2.28.0",
    "tqdm>=4.65.0",
    "setuptools>=61.0",
    "twine>=6.1.0",
    "build>=1.3.0",
]

[project.urls]
"Homepage" = "https://github.com/KisanThapa/kale"
"Bug Tracker" = "https://github.com/KisanThapa/kale/issues"
