[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "PgsFile"
version = "0.5.5"
authors = [
    { name = "Pan Guisheng", email = "panguisheng@sufe.edu.cn" }
]
description = "This module streamlines Python package management, script execution, file handling, web scraping, and multimedia downloads. It supports LLM-based NLP tasks like OCR, tokenization, lemmatization, POS tagging, NER, ATE, dependency parsing, MDD, WSD, LIWC, MIP analysis, text classification, and Chinese-English sentence alignment. Additionally, it generates word lists and data visualizations, making it a practical tool for data scraping and analysisâ€”ideal for literary students and researchers."
readme = "README.md"
license = { file = "LICENSE" }

requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: Free For Educational Use",
    "Operating System :: OS Independent",
]
dependencies = [
    "chardet",
    "pandas",
    "python-docx",
    "pip",
    "requests",
    "fake-useragent",
    "lxml",
    "pimht",
    "pysbd",
    "nlpir-python",
    "pillow",
    "liwc",
]

[project.urls]
Homepage = "https://github.com/Petercusin/PgsFile"
Repository = "https://github.com/Petercusin/PgsFile"

[tool.setuptools.packages.find]
where = ["src"]