[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "McSixAI"
version = "0.1.6"
description = "AI ассистент для программирования"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "requests>=2.28.0",
    "python-dotenv>=0.19.0"
]

[project.scripts]
mcsixai = "McSixAI.cli:main"