[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aic-sdk"
version = "1.0.2"
description = "Python bindings for the ai-coustics speech-enhancement SDK"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [{ name = "ai-coustics GmbH", email = "info@ai-coustics.com" }]
dependencies = ["numpy"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: C",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
]

[project.urls]
Homepage = "https://github.com/ai-coustics/aic-sdk-py"
Documentation = "https://ai-coustics.github.io/aic-sdk-py/"
Source = "https://github.com/ai-coustics/aic-sdk-py"
Issues = "https://github.com/ai-coustics/aic-sdk-py/issues"

[tool.aic-sdk]
sdk-version = "0.6.3"

[tool.ruff]
line-length = 120
src = ["aic", "tests"]
target-version = "py313"
lint.ignore = [
    "ASYNC230",
    "COM812",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "DTZ005",
    "EM101",
    "EM102",
    "PLR0913",
    "TRY002",
    "TRY003",
]
