[tool.poetry]
name = "opynsense"
version = "0.1.3"
description = "A Python library for interacting with OpnSense router OS through the REST API"
authors = ["Oliver Galbraith <olivergalbraith0@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"
homepage = "https://github.com/ollie-galbraith/opynsense"
repository = "https://github.com/ollie-galbraith/opynsense"
documentation = "https://github.com/ollie-galbraith/opynsense"

packages = [
    { include = "opynsense", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.8"
restpylot = "^0.1.1"

[tool.poetry.group.devs.dependencies]
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"