# pyproject.toml

[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pypho"
version = "0.0.4"
description = "Interactive photogrammetric design for geological objects"
readme = "README.md"
authors = [{ name = "Gautier Laurent", email = "gautier.laurent@univ-orleans.fr" }]
license-files = ["Licence_CeCILL-B_V1-en.txt"]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Development Status :: 2 - Pre-Alpha",
    "Framework :: Jupyter",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
]
keywords = ["photography", "photogrammetry", "geology"]
dependencies = [
    "pyvista",
    "pandas",
    "scipy",
    "meshio",
    "trame",
    "vtk >= 9.1",
    "trame-vtk",
    "trame-vuetify",
    "colorcet",
]
requires-python = ">=3.10"

[project.optional-dependencies]
nb = ["jupyter"]

[tool.setuptools]
packages  = ["pypho"]

[project.urls]
Homepage = "https://github.com/GeoISTO/PyPho"

[tool.bumpver]
current_version = "0.0.4"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pypho/__init__.py" = ["{version}"]
"pyproject.toml" = [
    'current_version = "{version}"',
    'version = "{version}"'
]

"README.md" = [
    "{version}",
]

