[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "py-mcp-client"
version = "0.0.8"
authors = [
  { name = "pytincture", email = "schapman1974@gmail.com" },
]
description = "A Python client for interacting with MCP servers via Server-Sent Events and JSON-RPC"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = []

[project.urls]
Homepage = "https://github.com/pytincture/py-mcp-client"
Repository = "https://github.com/pytincture/py-mcp-client.git"
Issues = "https://github.com/pytincture/py-mcp-client/issues"

[tool.hatch.build.targets.wheel]
packages = ["py_mcp_client"]