[project]
name = "amharicNLP"
version = "0.1.0"
description = """
amharicNLP is a Python package for Amharic Natural Language Processing (NLP) and text preprocessing. 
It provides tools for Amharic tokenization, text normalization, stopword removal, stemming, 
and sentiment analysis. The package is designed to support Ethiopian languages, with a focus 
on Amharic text processing for machine learning, deep learning, and AI applications. 
It is useful for Amharic data preprocessing, Amharic text classification, information retrieval, 
and other Amharic NLP tasks such as word segmentation, language modeling, and linguistic analysis.
"""

readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }

authors = [
  { name = "Yonas Abebe", email = "abebeyonas88@gmail.com" }
]

keywords = [
    "Amharic",
    "NLP",
    "Amharic NLP",
    "Amharic preprocessing",
    "Amharic tokenizer",
    "Amharic stopwords",
    "Amharic sentiment analysis",
    "Amharic text processing",
    "Ethiopian NLP",
    "tokenizer",
    "normalizer",
    "sentiment analysis",
    "amharicnlp",
    "amharicprocessing",
    "amharicnltk",
    "tokinization",   # keep common misspelling for search
    "amharicstopword"
]


classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Text Processing :: Linguistic",
    "Natural Language :: English",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License"
]


dependencies = [
    "numpy",
    "transformers",
    "torch",
    "regex"
]

[project.urls]
Homepage = "https://github.com/yonasab12/amharicNLP"
Repository = "https://github.com/yonasab12/amharicNLP"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
amharicNLP = [
    "data/*.txt",
    "resources/wordnet/*.json",  # Add this line
    "resources/*.json"           # Optional: include all JSON files in resources
]

