[project]
name = "path_extract"
version = "0.1.5"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aenum>=3.1.16",
    "altair>=5.5.0",
    "altair-transform>=0.2.0",
    "altair-viewer>=0.4.0",
    "beautifulsoup4>=4.13.4",
    "html5lib>=1.1",
    "ipykernel>=6.29.5",
    "ipython>=9.4.0",
    "jupyter>=1.1.1",
    "lxml>=6.0.0",
    "marimo[recommended]>=0.14.10",
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
    "pandas>=2.3.0",
    "polars>=1.31.0",
    "prefixed>=0.9.0",
    "pypalettes>=0.1.6",
    "pyprojroot>=0.3.0",
    "pytest>=8.4.1",
    "rich>=14.0.0",
    "ruff>=0.12.1",
    "vegafusion[embed]>=2.0.2",
    "vl-convert-python>=1.8.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
