[project]
name = "abdwp"
version = "0.4.7"
description = "Analyzing Baseball Data with Python"
readme = "README.md"
authors = [
    { name = "David Dalpiaz", email = "dalpiaz2@illinois.edu" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.1",
    "pandas>=2.3.0",
    "pybaseball>=2.2.7",
    "requests>=2.32.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "pytest>=8.4.1",
    "seaborn>=0.13.2",
]

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]
