[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
# can be empty if no extra settings are needed, presence enables setuptools-scm

[project.urls]
Homepage = "https://github.com/QUARK-framework/QUARK-plugin-tsp"

[project]
name = "QUARK-plugin-tsp"
dynamic = ["version"]
authors = [
    { name = "Philipp Ross", email = "philipp.ross@bmw.de" },
    { name = "Marvin Erdmann", email = "marvin.erdmann@bmw.de" },
    { name = "Andre Luckow", email = "andre.luckow@bmwgroup.com" },
    { name = "Greshma Shaji", email = "greshma.shaji@bmwgroup.com" },
    { name = "Florian Kiwit", email = "florian.kiwit@bmw.de" },
    { name = "Benjamin Decker", email = "benjamin.decker@bmw.de" },
]
description = "Quark plugin providing problem generation and mapping modules for the tsp problem"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "Apache-2.0"
dependencies = ["networkx>=3.4.2", "numpy>=2.2.3", "quark-framework>=0.4.1"]
