[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dustmaps3d"
version = "2.2.9"
description = "An all-sky 3D dust map based on Gaia and LAMOST."
readme = "README.md"
requires-python = ">=3.7.1"
license = {text = "MIT"}
authors = [
  {name = "Wang Tao", email = "wt@mail.bnu.edu.cn"}
]

classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
  "Topic :: Scientific/Engineering :: Astronomy"
]
dependencies = [
  "numpy",
  "pandas",
  "astropy",
  "astropy-healpix",
  "tqdm",
  "platformdirs",
  "requests"

]

[project.urls]
Homepage = "https://github.com/Grapeknight/dustmaps3d"

[tool.setuptools.packages.find]
where = ["."]
