[build-system]
requires = ["setuptools >= 77.0.3",
            "setuptools-scm>=8.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Epal"
version = "0.2.2"
authors = [
  { name="Lucius Landschulze", email="lucland278@gmail.com" },
]
description = "Entity component system for Python"

dependencies = [
    "pygame"
]

readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]


[project.urls]
Homepage = "https://github.com/lucilands/Epal"
Issues = "https://github.com/lucilands/Epal/issues"

[tool.setuptools.package-data]
epal = ["epal/asset_manager/null_asset.png"]
