[project]
name = "mkcd"
version = "1.0.7"
authors = [
  { name="Tanjim Kamal", email="tanjimkamal1@gmail.com" },
]
description = "Get Linux utilities like tail,head,cat,cd,ls,cp,mv,rm in Windows directly without needing to manage WSL"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: Microsoft :: Windows",
    "Environment :: Win32 (MS Windows)",
    "Topic :: Terminals",
    "Development Status :: 5 - Production/Stable"
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/itzmetanjim/mkcd"
Issues = "https://github.com/itzmetanjim/mkcd/issues"

[tool.setuptools.package-data]
mkcd = ["_bin/windows_x86_64/*"]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
mkcd-install = "mkcd:install"
mkcd-uninstall = "mkcd:uninstall"
ls = "mkcd.wrappers:ls_color"
grep = "mkcd.wrappers:grep_color"

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"