[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mlvlab"
version = "0.2.19"
description = "Visual AI Learning Ecosystem - MLVisual®"
readme = "docs/README_PyPI.md"
requires-python = ">=3.10"

# --- Dependencias Principales (Flexibles) ---
# ~=2.0 permite 2.0.2, 2.1, etc., pero no 3.0.
dependencies = [
    # Core de simulación y ciencia de datos
    "numpy~=2.2",
    "arcade~=3.3",
    "gymnasium~=1.2",
    "opencv-python~=4.12",
    "pyvirtualdisplay~=3.0",

    # Dependencias de la CLI
    "typer~=0.16",
    "rich>=13.0,<14.0",
    "moviepy~=2.2",
    "prompt_toolkit>=3.0,<4.0",

    # Dependencias de la UI (AnalyticsView)
    "nicegui[highcharts]~=2.22",
    "PySide6>=6.9,<6.10",
]

[project.optional-dependencies]
# Dependencias de desarrollo, aquí sí puedes ser más flexible con '>='
dev = [
    "pytest>=6.0.0",
    "black>=24.0.0",
    "isort>=5.10.0",
    "pipreqs>=0.4.13",
]

# --- Metadatos y Scripts ---
[project.scripts]
mlv = "mlvlab.cli.main:app"


[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
mlvlab = [
    "envs/*/assets/*", 
    "i18n/locales/*/*.json"
]