[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pythermonomics"
version = "0.0.2"
description = "Tools for geothermal techno-economics, including NPV, LCOE, well simulation, and more."
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }
authors = [{ name = "Stephan de Hoop", email = "stephan.dehoop@tno.nl" }]

keywords = ["geothermal", "energy", "npv", "lcoe", "economics", "techno-economics"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Operating System :: OS Independent",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering",
]

dependencies = [
  "numpy_financial",
  "numpy",
  "pandas",
  "pydantic",
  "pyyaml",
]

[project.optional-dependencies]
docs = [
  "mkdocs",
  "mkdocstrings[python]",
  "mkdocs-material",
  "mike",
]
tests = [
  "pytest",
]
notebook = [
  "jupyterlab>=4",
  "ipykernel>=6",
  "ipywidgets>=8",
  "matplotlib>=3.8",
  "plotly>=5.20",
]

[project.scripts]
pythermonomics = "pythermonomics.cli:main" 

[project.urls]
Homepage = "https://github.com/TNO/pythermonomics"
Repository = "https://github.com/TNO/pythermonomics"
# Documentation = "https://your-docs-url"
Issues = "https://github.com/TNO/pythermonomics/issues"

[tool.setuptools]
# include-package-data = true

[tool.setuptools.packages.find]
where = ["src"] 

[tool.isort]
profile = "black"
line_length = 88

[tool.black]
line-length = 88
target-version = ["py39"]
